export const FETCH_FILMS_START = 'FETCH_FILMS_START';
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
export const FETCH_FILMS_FAILURE = 'FETCH_FILMS_FAILURE';

export const FETCH_FILMS_BY_SEARCH_START = 'FETCH_FILMS_BY_SEARCH_START';
export const FETCH_FILMS_BY_SEARCH_SUCCESS = 'FETCH_FILMS_BY_SEARCH_SUCCESS';
export const FETCH_FILMS_BY_SEARCH_FAILURE = 'FETCH_FILMS_BY_SEARCH_FAILURE';

export const FETCH_FILM_BY_ID_START = 'FETCH_FILM_BY_ID_START';
export const FETCH_FILM_BY_ID_SUCCESS = 'FETCH_FILM_BY_ID_SUCCESS';
export const FETCH_FILM_BY_ID_FAILURE = 'FETCH_FILM_BY_ID_FAILURE';

export const FETCH_ACTOR_BY_ID_START = 'FETCH_ACTOR_BY_ID_START';
export const FETCH_ACTOR_BY_ID_SUCCESS = 'FETCH_ACTOR_BY_ID_SUCCESS';

export const FETCH_PERSONS_START = 'FETCH_PERSONS_START';
export const FETCH_PERSONS_SUCCESS = 'FETCH_PERSONS_SUCCESS';
export const FETCH_PERSONS_FAILURE = 'FETCH_PERSONS_FAILURE';

export const SEARCH_FILM = 'SEARCH_FILM';